apiVersion: v1
kind: Namespace
metadata:
  name: counter-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-deploy
  namespace: counter-ns
  labels:
    app: counter-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-counter-app
  template:
    metadata:
      labels:
        app: node-counter-app
    spec:
      containers:
        - name: node-counter-ctr
          image: index.docker.io/guyrotem/node-counter:1.2
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: counter-svc
  name: counter-svc
  namespace: counter-ns
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  selector:
    app: node-counter-app
  type: NodePort
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curling
  namespace: counter-ns
spec:
  schedule: 0/1 * * * *
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curling-ctr
              image: index.docker.io/library/buildpack-deps:19.10-curl
              command: ["sh", "-c", "curl --fail -X POST -v http://counter-svc.counter-ns:8081/inc"]
          restartPolicy: OnFailure
